"""Build resumable Qwen3 1536-dimension shadow embeddings.

Messages are rebuilt from the canonical ``messages`` table and chunked with
Honcho's normal tokenizer/chunker. This deliberately avoids carrying forward
legacy duplicate or overlong rows from ``message_embeddings``. Documents are
short in this deployment and continue to use the ``embedding_v1536`` shadow
column on ``documents``.
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import json
import logging
import os
import signal
import time
from dataclasses import dataclass
from typing import Any, Final, cast

import numpy as np
import psycopg
from pgvector.psycopg import register_vector

from src.embedding_client import embedding_client

MIGRATION_NAME: Final = "qwen3_embedding_8b_1536_20260711"
EXPECTED_DIMENSIONS: Final = 1536
logger = logging.getLogger("honcho.embedding_migration.chunked")
stopping = False


@dataclass
class SourceMessage:
    message_id: str
    content: str
    workspace_name: str
    session_name: str
    peer_name: str
    created_at: Any


def _stop(_signum: int, _frame: Any) -> None:
    global stopping
    stopping = True


def _connection_uri() -> str:
    return os.environ["DB_CONNECTION_URI"].replace(
        "postgresql+psycopg://", "postgresql://"
    )


def _connect() -> psycopg.Connection[Any]:
    conn = psycopg.connect(_connection_uri(), autocommit=False)
    register_vector(conn)
    with conn.cursor() as cur:
        cur.execute("SET statement_timeout = 0")
        cur.execute("SET lock_timeout = '5s'")
    conn.commit()
    return conn


def _ensure_schema(conn: psycopg.Connection[Any]) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS message_embeddings_v1536_shadow (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content text NOT NULL,
                embedding vector(1536) NOT NULL,
                message_id text NOT NULL,
                workspace_name text NOT NULL,
                session_name text NOT NULL,
                peer_name text NOT NULL,
                created_at timestamptz NOT NULL,
                sync_state text NOT NULL DEFAULT 'synced',
                last_sync_at timestamptz,
                sync_attempts integer NOT NULL DEFAULT 0,
                chunk_index integer NOT NULL,
                CONSTRAINT uq_message_embeddings_v1536_source_chunk
                    UNIQUE (message_id, chunk_index)
            )
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS
                ix_message_embeddings_v1536_shadow_source
            ON message_embeddings_v1536_shadow (message_id)
            """
        )
    conn.commit()


def _fetch_messages(
    conn: psycopg.Connection[Any], batch_size: int
) -> list[SourceMessage]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT m.public_id, m.content, m.workspace_name, m.session_name,
                   m.peer_name, m.created_at
            FROM messages AS m
            WHERE btrim(m.content) <> ''
              AND NOT EXISTS (
                  SELECT 1
                  FROM message_embeddings_v1536_shadow AS s
                  WHERE s.message_id = m.public_id
              )
            ORDER BY m.id
            LIMIT %s
            """,
            (batch_size,),
        )
        return [SourceMessage(*row) for row in cur.fetchall()]


def _prepare_message_chunks(
    messages: list[SourceMessage],
) -> list[tuple[SourceMessage, int, str]]:
    prepared: list[tuple[SourceMessage, int, str]] = []
    for message in messages:
        # Honcho chunks token IDs and decodes them back to text. At a multibyte
        # boundary, re-encoding that decoded text can very rarely add one token
        # (for example 2048 -> 2049). Feed every result back through Honcho's
        # own chunker until it considers the text stable; do not maintain a
        # separate migration-specific chunking algorithm.
        pending = [message.content]
        stable_chunks: list[str] = []
        while pending:
            candidate = pending.pop(0)
            chunks = embedding_client.prepare_chunks({"chunk": candidate})["chunk"]
            if len(chunks) == 1 and chunks[0] == candidate:
                stable_chunks.append(candidate)
            else:
                pending[0:0] = chunks
            if len(stable_chunks) + len(pending) > 1000:
                raise RuntimeError(
                    f"Chunk stabilization exceeded safety limit for {message.message_id}"
                )
        prepared.extend(
            (message, chunk_index, chunk)
            for chunk_index, chunk in enumerate(stable_chunks)
        )
    return prepared


async def _embed(texts: list[str]) -> list[list[float]]:
    return await embedding_client.simple_batch_embed(texts)


def _validate(vectors: list[list[float]], expected_count: int) -> None:
    if len(vectors) != expected_count:
        raise RuntimeError(
            f"Embedding result count mismatch: expected={expected_count} got={len(vectors)}"
        )
    bad = next((len(vector) for vector in vectors if len(vector) != 1536), None)
    if bad is not None:
        raise RuntimeError(
            f"Embedding dimension mismatch: expected={EXPECTED_DIMENSIONS} got={bad}"
        )


def _migrate_messages(conn: psycopg.Connection[Any], batch_size: int) -> bool:
    messages = _fetch_messages(conn, batch_size)
    if not messages:
        return False

    started = time.monotonic()
    chunks = _prepare_message_chunks(messages)
    vectors = asyncio.run(_embed([chunk for _message, _index, chunk in chunks]))
    _validate(vectors, len(chunks))
    params = [
        (
            chunk,
            np.asarray(vector, dtype=np.float32),
            message.message_id,
            message.workspace_name,
            message.session_name,
            message.peer_name,
            message.created_at,
            chunk_index,
        )
        for (message, chunk_index, chunk), vector in zip(chunks, vectors, strict=True)
    ]
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO message_embeddings_v1536_shadow
                (content, embedding, message_id, workspace_name, session_name,
                 peer_name, created_at, sync_state, last_sync_at, chunk_index)
            VALUES (%s, %s, %s, %s, %s, %s, %s, 'synced', now(), %s)
            ON CONFLICT (message_id, chunk_index) DO NOTHING
            """,
            params,
        )
    conn.commit()
    elapsed = max(time.monotonic() - started, 1e-9)
    logger.info(
        "source=messages messages=%s chunks=%s rate=%.2f chunks/s",
        len(messages),
        len(chunks),
        len(chunks) / elapsed,
    )
    _record_progress(conn, "messages", len(chunks) / elapsed)
    return True


def _fetch_documents(
    conn: psycopg.Connection[Any], batch_size: int
) -> list[tuple[str, str]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, content FROM documents
            WHERE embedding_v1536 IS NULL
            ORDER BY id LIMIT %s
            """,
            (batch_size,),
        )
        return list(cur.fetchall())


def _migrate_documents(conn: psycopg.Connection[Any], batch_size: int) -> bool:
    rows = _fetch_documents(conn, batch_size)
    if not rows:
        return False
    started = time.monotonic()
    vectors = asyncio.run(_embed([content for _row_id, content in rows]))
    _validate(vectors, len(rows))
    with conn.cursor() as cur:
        cur.executemany(
            """
            UPDATE documents SET embedding_v1536 = %s
            WHERE id = %s AND embedding_v1536 IS NULL
            """,
            [
                (np.asarray(vector, dtype=np.float32), row_id)
                for (row_id, _content), vector in zip(rows, vectors, strict=True)
            ],
        )
    conn.commit()
    elapsed = max(time.monotonic() - started, 1e-9)
    logger.info("source=documents rows=%s rate=%.2f/s", len(rows), len(rows) / elapsed)
    _record_progress(conn, "documents", len(rows) / elapsed)
    return True


def _record_progress(
    conn: psycopg.Connection[Any], active_source: str, recent_rate: float
) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
              (SELECT count(DISTINCT message_id)
               FROM message_embeddings_v1536_shadow),
              (SELECT count(*) FROM message_embeddings_v1536_shadow),
              (SELECT count(*) FROM messages WHERE btrim(content) <> ''),
              (SELECT count(*) FROM documents
               WHERE embedding_v1536 IS NOT NULL),
              (SELECT count(*) FROM documents)
            """
        )
        counts = cast(
            tuple[int, int, int, int, int] | None,
            cur.fetchone(),
        )
        if counts is None:
            raise RuntimeError("Failed to read embedding migration counts")
        message_count, chunk_count, message_total, document_count, document_total = (
            counts
        )
        payload = {
            "strategy": "canonical_messages_chunked_2048",
            "active_source": active_source,
            "messages_completed": int(message_count),
            "message_chunks_completed": int(chunk_count),
            "messages_total": int(message_total),
            "documents_completed": int(document_count),
            "documents_total": int(document_total),
            "recent_rate_per_second": round(recent_rate, 3),
            "worker_host": os.uname().nodename,
        }
        cur.execute(
            """
            UPDATE embedding_migration_state
            SET updated_at = now(), metadata = metadata || %s::jsonb
            WHERE migration_name = %s
            """,
            (json.dumps(payload), MIGRATION_NAME),
        )
    conn.commit()


def _record_error(conn: psycopg.Connection[Any], error: BaseException) -> None:
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE embedding_migration_state
                SET updated_at = now(), metadata = metadata || %s::jsonb
                WHERE migration_name = %s
                """,
                (
                    json.dumps(
                        {
                            "last_error": f"{type(error).__name__}: {error}"[:2000],
                            "last_error_at_epoch": time.time(),
                        }
                    ),
                    MIGRATION_NAME,
                ),
            )
        conn.commit()
    except Exception:
        conn.rollback()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--message-batch-size", type=int, default=128)
    parser.add_argument("--document-batch-size", type=int, default=128)
    parser.add_argument("--retry-seconds", type=float, default=15.0)
    parser.add_argument("--empty-passes", type=int, default=2)
    parser.add_argument("--max-cycles", type=int, default=0)
    args = parser.parse_args()
    if not 1 <= args.message_batch_size <= 512:
        raise SystemExit("--message-batch-size must be between 1 and 512")
    if not 1 <= args.document_batch_size <= 512:
        raise SystemExit("--document-batch-size must be between 1 and 512")

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    signal.signal(signal.SIGTERM, _stop)
    signal.signal(signal.SIGINT, _stop)

    conn: psycopg.Connection[Any] | None = None
    empty_passes = 0
    completed_cycles = 0
    while not stopping:
        try:
            if conn is None or conn.closed:
                conn = _connect()
                _ensure_schema(conn)
            did_work = _migrate_messages(conn, args.message_batch_size)
            if not stopping:
                did_work |= _migrate_documents(conn, args.document_batch_size)
            if did_work:
                completed_cycles += 1
                if args.max_cycles and completed_cycles >= args.max_cycles:
                    break
                empty_passes = 0
                continue
            empty_passes += 1
            logger.info("No pending rows found (empty pass %s)", empty_passes)
            if empty_passes >= args.empty_passes:
                break
            time.sleep(5)
        except Exception as exc:
            logger.exception("Migration batch failed; retrying")
            if conn is not None:
                _record_error(conn, exc)
                with contextlib.suppress(Exception):
                    conn.close()
                conn = None
            time.sleep(args.retry_seconds)

    if conn is not None and not conn.closed:
        conn.close()
    logger.info("Chunked migration worker stopped")


if __name__ == "__main__":
    main()
